# Site and content
site_name: "Safespring documentation"
docs_dir: "content"

# Github integration
repo_name: "safespring/docs"
repo_url: "https://github.com/safespring/docs"
edit_uri: "edit/master/content/"

# Safespring theme
theme:
  name: "material"
  feature:
    tabs: false
  logo: "safespring_symbol_white_svg.svg"
  favicon: "favicon.ico"
extra_css:
  - "safespring.css"
extra_javascript:
  - "https://lbpj80qtys85.statuspage.io/embed/script.js"
extra:
  font:
    text: "Montserrat"
    code: "Ubuntu Mono"

# https://squidfunk.github.io/mkdocs-material/getting-started/#extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables

# Pages layout
nav:
  - Overview: "index.md"
  - Backup:
      - Quick-Start Guide: "backup/quickstart-guide.md"
      - Installation:
          - Overview: "backup/install/overview.md"
          - Linux: "backup/install/linux.md"
          - Windows: "backup/install/windows.md"
          - macOS: "backup/install/apple-macos.md"
          - freeBSD: "backup/install/freebsd-other.md"
          - Application:
              - Microsoft SQL Server: "backup/install/mssql-windows.md"
      - HOWTOs:
          - Back up Files: "backup/howto/back-up-files.md"
          - Consumption Units: "backup/howto/consumption-units.md"
          - Business Units: "backup/howto/business-units.md"
          - Passwords: "backup/howto/password.md"
          - Deleting Nodes: "backup/howto/delete-node.md"
          - Email Reports: "backup/howto/reports-by-email.md"
          - Encryption: "backup/howto/encryption.md"
          - Include/Exclude: "backup/howto/include-exclude.md"
          - Admin SSO: "backup/howto/sso.md"
          - Handling Changing Files: "backup/howto/changing-files.md"
          - List Files: "backup/howto/list-files.md"
          - Linux GUI: "backup/howto/linux-gui.md"
      - Automation:
          - Command Line: "backup/automation/cli-tool.md"
          - REST API: "backup/automation/rest-api.md"
          - API Resources: "backup/automation/api-resources.md"
          - More Info: "backup/automation/more-info.md"
      # - Performance:
      #   - First Backup: "backup/performance/first-backup.md"
      - Recovery:
          - The Basics: "backup/recovery/basics.md"
          - Linux Systems: "backup/recovery/linux-recovery.md"
          - Windows Systems: "backup/recovery/windows-recovery.md"
          - Testing: "backup/recovery/testing.md"
          - Encryption: "backup/recovery/encryption.md"
      - Cloud Backup:
          - Microsoft 365: "backup/cloud/microsoft-365.md"
          - Microsoft Entra ID: "backup/cloud/microsoft-entra-id.md"
          - User Data Recovery: "backup/cloud/user-data-recovery.md"
          - Read PST files: "backup/cloud/pst-files.md"
      - FAQ: "backup/faq.md"
      - Legacy Backup: "legacy-backup/index.md"
  - Compute:
      - Getting Started: "compute/getting-started.md"
      - VPN options: "compute/vpn.md"
      - API Access: "compute/api.md"
      - Flavors: "compute/flavors.md"
      - Application credentials: "compute/app-creds.md"
      - Trouble Shooting: "compute/troubleshooting.md"
      - HOWTOs:
          - Using Keypairs: "compute/howto/keypairs.md"
          - Persistent IP address: "compute/howto/persistent-ip-address.md"
          - Windows images: "compute/howto/windows.md"
          - Migrate instance to another project: "compute/howto/migrate-between-projects.md"
          - Taking snapshots of instances: "compute/howto/snapshotting-instances.md"
  - Storage:
      - General S3 Info: "storage/generalinfo.md"
      - S3 Quotas: "storage/quota.md"
      - Example s3cmd config: "storage/s3cmd.md"
      - S3 Advanced Features: "storage/s3-advanced.md"
      - S3 Usage Report: "storage/usage-statistics.md"
      - Example s3fs config: "storage/s3fs.md"
      - Example CloudBerry config: "storage/cloudberry.md"
      - Example CyberDuck config: "storage/cyberduck.md"
      - Example Duck CLI config: "storage/duck-cli.md"
      - Example Minio Client config: "storage/minio-client.md"
      - Example AWS-CLI config: "storage/aws-cli.md"
      - Example NextCloud S3 integration: "storage/nextcloud-s3.md"
      - Tips and Tricks: "storage/tips-n-tricks.md"
      - Backup Exec and Safespring Storage: "storage/backup-exec.md"
      - Other Backends: "storage/other-backends.md"
      - Object Locking: "storage/object-locking.md"
  - Status and support:
      - Roadmap: "service/roadmap.md"
      - Status information: "service/status.md"
      - Offboarding information: "new/offboarding.md"
      - Getting support: "service/support.md"
      - Policies and SLA: "service/policies.md"
      - Known issues: "service/known_issues.md"
      - Contributing: "contribute.md"
